import Head from 'next/head'
import { GraphQLClient, gql } from 'graphql-request'

const hygraph = new GraphQLClient('https://api-sa-east-1.hygraph.com/v2/clgid9s1c27x401ug1lf64rak/master')
  const QUERY = gql`
  query Posts {
    posts {
      date
      id
      slug
      image {
        url
      }
      content{
        html
      }
      title
    }
  }
  `

export async function getStaticProps() {
  const { posts } = await hygraph.request(QUERY)

  return {
    props: {
      posts
    },
    revalidate: 10
  };
}

export default function Home({posts}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {posts.map((post) => {
          return (
            <div>
              {post.title}
            </div>
          )
        })}
      </div>
    </>
  )
}
