import Head from 'next/head'
import { GraphQLClient, gql } from 'graphql-request'
import PostCard from '@/components/PostCard'

const hygraph = new GraphQLClient('https://api-sa-east-1.hygraph.com/v2/clgid9s1c27x401ug1lf64rak/master')
  const QUERY = gql`
  query Posts {
    posts {
      date
      slug
      image {
        url
      }
      title
    }
  }
  `

export async function getStaticProps() {
  const { posts } = await hygraph.request(QUERY)

  return {
    props: {
      posts
    },
    revalidate: 10
  };
}

export default function Home({posts}) {
  let orderedPosts = posts.sort((a, b) => {
    return new Date(b.date) - new Date (a.date)
  })
  console.log("ordenados", orderedPosts)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {posts.map((post) => {
          console.log(post)
          return (
            <PostCard title= {post.title} image={post.image.url} date={post.date} slug={post.slug}/>
          )
        })}
      </div>
    </>
  )
}
